### ISSUE TITLE
Error starting lxc container

### ISSUE THREAD

**Issue by leon1995** [pimox/repo#3]
Hi,

when starting an lxc container I get the following log output:
```
lxc-start 100 20210517191642.271 ERROR    start - start.c:start:2090 - Exec format error - Failed to exec "/sbin/init"
lxc-start 100 20210517191642.271 ERROR    sync - sync.c:__sync_wait:36 - An error occurred in another process (expected sequence number 7)
lxc-start 100 20210517191642.272 ERROR    start - start.c:__lxc_start:1999 - Failed to spawn container "100"
lxc-start 100 20210517191644.915 ERROR    lxc_start - tools/lxc_start.c:main:308 - The container failed to start
```

I hope you can help me :)

**Comment by gratuxri** [comment]
Can you try this lxc templates in /var/lib/vz/template/cache/
https://jenkins.linuxcontainers.org/view/Images/job/image-debian/architecture=arm64,release=bullseye,variant=default/lastSuccessfulBuild/artifact/rootfs.tar.xz
https://jenkins.linuxcontainers.org/view/Images/job/image-alpine/architecture=arm64,release=3.13,variant=default/lastSuccessfulBuild/artifact/rootfs.tar.xz

**Comment by leon1995** [comment]
Hey,
I solced it similarly. I downloaded the template for arm manually via the jenkins link and imported it
