### ISSUE TITLE
No memory in Summary of LXC

### ISSUE THREAD

**Issue by techsolo12** [pimox/repo#5]
Hello,

when a had run a LXC Container there is no memory usage in summary.
When i open the bash and use `htop` there is the memory and swap usage from the host.
The CPU usage and anything else is from the guest.

![Unbenannt](https://user-images.githubusercontent.com/36322543/121223081-72608380-c887-11eb-9ccd-b84c32403892.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/36322543/121223192-90c67f00-c887-11eb-87f4-6b8267b9663a.PNG)

**Comment by short997** [comment]
Please add _cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1_ to **/boot/cmdline.txt** followed by a reboot.

**Comment by techsolo12** [comment]
Very good, it works! Thank you for your help.
